# Zabbix | Postgres | Grafana | PhpIPAM
version: "3.7"
services:
  zb-server: ### ZABBIX ------------------------------------- ZB SERVER
    container_name: zb-server
    hostname: zb-server
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    restart: always
    environment:
      DB_SERVER_HOST: pg-zb-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_CACHESIZE: 500M
      ZBX_CACHEUPDATEFREQUENCY: 60
      ZBX_STARTPINGERS: 5
      ZBX_HISTORYCACHESIZE: 64M
      ZBX_HISTORYINDEXCACHESIZE: 16M
    depends_on:
      - pg-zb-server
    links:
      - pg-zb-server
    volumes:
      - /var/zb-server-alerts:/usr/lib/zabbix/alertscripts
      - /var/zb-server-mibs:/var/lib/zabbix/mibs
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      default:
            aliases:
              - zb-server  ## Set Alias

  pg-zb-server: ### ZABBIX ----------------------------------- |DB|> ZB-SERVER|ZB-WEB
    container_name: pg-zb-server
    hostname: pg-zb-server
    image: postgres:12.4-alpine
    restart: on-failure
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - 8097:5432
    volumes:
      - /var/pg-zb-server:/var/lib/postgresql/data
      - ./MIGRATE/ZABBIX-DB.gz:/MIGRATE.gz
    networks:
      default:
            aliases:
              - pg-zb-server  ## Set Alias
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  zb-web: ### ZABBIX ---------------------------------------- WEB
    container_name: zb-web
    hostname: zb-web
    image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0-latest
    restart: on-failure
    environment:
      DB_SERVER_HOST: pg-zb-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zb-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Sao_Paulo"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - zb-server           # ZB server
      - pg-zb-server        # PG Zabbix
    links:
      - pg-zb-server
      - zb-server
    ports:
      - 8090:8080
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      default:
            aliases:
              - zb-web  ## Set Alias

  zb-agent: ### ZABBIX ---------------------------------------- AGENT
    container_name: zb-agent
    hostname: zb-agent
    image: zabbix/zabbix-agent:alpine-5.0-latest
    privileged: true
    restart: unless-stopped
    environment:
      - ZBX_HOSTNAME=zb-server
      - ZBX_SERVER_HOST=zb-server
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    links:
      - zb-server
    networks:
      default:
            aliases:
              - zb-agent  ## Set Alias

  grafana: ### GRAFANA ---------------------------------------- WEB
    container_name: gf-web
    hostname: grafana
    image: grafana/grafana:7.2.1
    ports:
      - 8091:3000
    depends_on:
      - pg-grafana # Dependente de subir o DB primeiro
    links:
      - pg-grafana # Linka com o Banco de dados
    environment:
      - GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app
      - GF_SESSION_PROVIDER=redis
      - GF_SESSION_PROVIDER_CONFIG=addr=redis:6379,pool_size=100,db=grafana
#      - GF_SESSION_PROVIDER_CONFIG=user=grafana password=grafana host=pg-grafana port=5432 dbname=grafana sslmode=disable=
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_DATABASE_HOST=pg-grafana:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=${GF_DATABASE_USER}
      - GF_DATABASE_PASSWORD=${GF_DATABASE_PASSWORD}
      - GF_DATABASE_TYPE=postgres
      - GF_SESSION_PROVIDER=postgres
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      default:
            aliases:
              - grafana  ## Set Alias

  pg-grafana: ### POSTGRE PARA O GRAFANA ---------------------------------------- DB GRAFANA-WEB
    container_name: pg-grafana
    hostname: pg-grafana
    image: postgres:12.2-alpine
    restart: on-failure
    ports:
    - 8096:5432
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: ${GF_DATABASE_USER}
      POSTGRES_PASSWORD: ${GF_DATABASE_PASSWORD}
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/pg-grafana-data:/var/lib/postgresql/data
    networks:
      default:
            aliases:
              - pg-grafana  ## Set Alias
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis: ### REDIS -> GRAFANA
    container_name: gf-redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  phpipam-web: ### PHPIPAM ---------------------------------------- WEB
    container_name: phpipam-web
    hostname: phpipam-web
    image: phpipam/phpipam-www:1.4x
    ports:
      - 8092:80
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - IPAM_DATABASE_WEBHOST=%
    restart: unless-stopped
    volumes:
      - /var/phpipam-logo:/phpipam/css/images/logo
      - ./MIGRATE/PHPIPAM.gz:/phpipam/db/MIGRATE.gz
    depends_on:
      - phpipam-mariadb
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  phpipam-mariadb: ### PHPIPAM ---------------------------------------- DB WEB
    container_name: phpipam-mariadb
    hostname: phpipam-mariadb
    image: mariadb:10.5.5
    ports:
      - 8095:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${IPAM_DATABASE_PASS}
    restart: unless-stopped
    volumes:
      - /var/phpipam-db-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  phpipam-cron: ### Cron
    container_name: phpipam-cron
    hostname: phpipam-cron
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=${IPAM_DATABASE_PASS}
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
