# Zabbix | Postgres | Grafana |
version: "3.7"
services:
  zabbix-server: ### ZABBIX ------------------------------------- ZB SERVER
    container_name: zb-server
    hostname: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-5.0-latest
    restart: always
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_CACHESIZE: 500M
      ZBX_CACHEUPDATEFREQUENCY: 60
      ZBX_STARTPINGERS: 5
    depends_on:
      - postgres-server
    links:
      - postgres-server
    volumes:
      - /var/zb-server-alerts:/usr/lib/zabbix/alertscripts
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      default:
            aliases:
              - zabbix-server  ## Set Alias

  postgres-server: ### ZABBIX ----------------------------------- DB --- ZB-SERVER / WEB
    container_name: pg-zb-server
    hostname: postgres-server
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/pg-zb-server:/var/lib/postgresql/data
    networks:
      default:
            aliases:
              - postgres-server  ## Set Alias

  ##################################
  ################################## FIM ZABBIX SERVER
  ##################################

  zabbix-web: ### ZABBIX ---------------------------------------- WEB
    container_name: zb-web
    hostname: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    restart: on-failure
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Sao_Paulo"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server          ### POSTGREE-WEB
      - zabbix-server         ### ZB-SERVER
    links:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:8080
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      default:
            aliases:
              - zb-web  ## Set Alias

  ##################################
  ################################## FIM ZABBIX WEB
  ##################################

  zb-agent: ### ZABBIX - AGENT
    container_name: zb-agent
    hostname: zb-agent
    image: zabbix/zabbix-agent:latest
    privileged: true
    restart: unless-stopped
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=zabbix-server
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    links:
      - zabbix-server
    networks:
      default:
            aliases:
              - zb-agent  ## Set Alias

  grafana: ### GRAFANA
    container_name: gf-web
    hostname: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - pg-grafana ### Dependente de subir o DB primeiro
    links:
      - pg-grafana ### Linka com o Banco de dados
    environment:
      - GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app
      - GF_SESSION_PROVIDER=redis
      - GF_SESSION_PROVIDER_CONFIG=addr=redis:6379,pool_size=100,db=grafana
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://grafana.localhost.com.br
      - GF_SESSION_PROVIDER_CONFIG=user=grafana password=grafana host=pg-grafana port=5432 dbname=grafana sslmode=disable=
      - GF_DATABASE_HOST=pg-grafana:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=grafana
      - GF_DATABASE_TYPE=postgres
      - GF_SESSION_PROVIDER=postgres
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      default:
            aliases:
              - grafana  ## Set Alias

  pg-grafana: ### POSTGRE PARA O GRAFANA
    container_name: pg-grafana
    hostname: pg-grafana
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
      POSTGRES_DB: grafana
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/pg-grafana-data:/var/lib/postgresql/data
    networks:
      default:
            aliases:
              - pg-grafana  ## Set Alias

  redis: ### REDIS -> GRAFANA
    container_name: gf-redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
